### ISSUE TITLE
Context.clone() method used by macros is private to the crate

### ISSUE THREAD

**Issue by St4NNi** [clarkmcc/cel-rust#30]
The official [cel-spec](https://github.com/google/cel-spec/blob/master/doc/langdef.md#macros) has some additional macros / functions that might be useful for some of our use cases like: `exists` or `exists_one`.

Unfortunately I am not able to implement them by myself because: `Context.clone()` is `pub(crate)` and not `pub`:

https://github.com/clarkmcc/cel-rust/blob/f4fa854f7b2ed0e9b41a9f1c477dc8d30dbdbeb6/interpreter/src/context.rs#L115

Am I missing something or wouldn't it be useful to provide the clone functionality and context shadowing also for custom extension functions?

**Comment by clarkmcc** [comment]
Hi! Yes, it definitely makes sense to expose that. I'll get a fix released. Thanks!

**Comment by clarkmcc** [comment]
Fixed. Using the main branch you should be able to clone the context now. I created a new issue #32  for the missing macros.
