### ISSUE TITLE
Regex support?

### ISSUE THREAD

**Issue by alexsnaps** [clarkmcc/cel-rust#48]
This is more of a question really than an actual issue... for now at least. 

If I read the cel spec properly, it is expected it'd support regular expressions, re2 based flavor.

Trying this out:

```rust
#[test]
fn test_matches() {
  let tests = vec![
      ("map", "{1: 'abc', 2: 'def', 3: 'ghi'}.all(key, key.matches('^[a-zA-Z]*$')) == true"),
      ("string", "'foobar'.matches('^[a-zA-Z]*$') == true"),
  ];

  for (name, script) in tests {
      assert_eq!(test_script(script, None), Ok(true.into()), "{}", name);
  }
}
```

I'm getting a `Err(NoSuchKey("matches"))` for both `map` & `string` tests. Couldn't see anything mentioning regular expressions neither. So here's the questions, is this a conscious decision to _not support_ them? Looking around, I couldn't find a good candidate regex lib to start implementing that support actually... especially as in our use-case we're looking at targeting wasm... 

Have you considered that side of the spec? Any conclusion you came to already?

**Comment by clarkmcc** [comment]
Definitely not intentional, it's been more a lack of demand than anything. I'll definitely get this on the priority list, or I would be happy to work through a PR with you if you'd like to take a stab at it as well. Otherwise I'll take a look later this week.

**Comment by alexsnaps** [comment]
Great! I'm certainly willing to have a shot at this, as if I can make it work here, I don't have to support two different code path in my own on-going work (see [here](https://github.com/Kuadrant/wasm-shim/pull/41), tho I'm rewriting the entire support for typing leveraging CEL, as that's how many types are actually represented with [Envoy](https://www.envoyproxy.io/) anyways). 
I'll look at supporting this while keeping it all working in wasm too then tho. I'll start looking around for a way to support that and will report my findings here. If you have any leads, now or later, please drop them here too 🙏 
Thanks for the awesome work you've done on CEL for Rust already!

**Comment by alexsnaps** [comment]
Looks like [regex](https://github.com/rust-lang/regex) would do the job... I'll start looking into leveraging it to add support for regex in the interpreter
