### ISSUE TITLE
Is `.size()` on a value not supported? Only `size(value)`?

### ISSUE THREAD

**Issue by polarathene** [clarkmcc/cel-rust#82]
`'hello'.size()` seems to fail with:

```
Err(InvalidArgumentCount { expected: 1, actual: 0 })
```

Is this a limitation or bug of `cel-rust` implementation? The [CEL spec for string methods](https://github.com/google/cel-spec/blob/master/doc/langdef.md#string-functions) notes `<string>.size()` in addition to `size(<string>)`.

**Comment by clarkmcc** [comment]
Thanks for reporting! I've pushed a fix in #88
