### ISSUE TITLE
Add to_string for AST

### ISSUE THREAD

**Issue by jrandolf** [clarkmcc/cel-rust#84]
This is useful for custom interpreters for showing which fragment in a parsed CEL expression is not supported/fails on.

**Comment by clarkmcc** [comment]
Can you elaborate on the use-case? If there's an issue parsing the CEL expression, then you wouldn't have an expression to to_string on.

**Comment by jrandolf** [comment]
Our interpreter builds an SQL query by walking the AST. When it faces some unsupported expression, we used to throw saying "Hey, this is not supported: {expression stringified}".

It's also very useful for debugging!

**Comment by jrandolf** [comment]
We currently walk the AST to build an SQL query. If the SQL query can't be built (perhaps due to some unknown field or gibberish expression being sent), we send back the fragment that failed to build.

This is also useful for debugging

**Comment by clarkmcc** [comment]
I guess what I don't understand is if there's was a problem with the CEL expression itself, then it wouldn't parse at all. If it does parse, the CEL expression is good. If you want to get a string representation of the expression, how is that any different than the input string CEL expression that was parsed? Aren't those virtually always identical?

Maybe providing more details about your example would help me understand. Looking through the PR it just seems like you're doing the inverse of parsing and producing exactly the same string that you parsed, so I don't know why you can't just look at the input string that was parsed.

**Comment by jrandolf** [comment]
Let's say you have `points > 0 && statis == PLAYING`. In this scenario, we are querying for games that are in play and have a positive number of points. The CEL is fine, but the builder will have a problem because statis should be spelled status which is the actual column name. Thus we throw that fragment of the expression; i.e. `statis == PLAYING`.

**Comment by clarkmcc** [comment]
I assume that you're using the parser only, and not the interpreter, is that correct?

**Comment by jrandolf** [comment]
> I assume that you're using the parser only, and not the interpreter, is that correct?

Indeed.

**Comment by jrandolf** [comment]
We've decided to work with an internal library. Feel free to close or merge the PR.

**Comment by clarkmcc** [comment]
> We've decided to work with an internal library. Feel free to close or merge the PR.

Sounds good, I'm going to close this issue. I'm happy to consider it further, but I'd like to understand better why converting from an expression to a string is useful when you already have the string that produced the expression in the first place. This seems potentially redundant.

    string -> AST -> string

Happy to consider more cases where that's not the case though.
